version: "3.4"

services:
  localstack:
    container_name: "localstack"
    image: "localstack/localstack:0.14.0"
    ports:
      - "4566:4566"
    environment:
      SERVICES: "kms"
      EDGE_BIND_HOST: "0.0.0.0"
      EDGE_PORT: "4566"
      HOSTNAME_EXTERNAL: "docker-host"
      PERSIST_ALL: "false"
      LS_LOG: "trace-internal"
      DEBUG: "1"